#!/usr/bin/env node

import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function parseReadme() {
    const readmePath = path.join(process.cwd(), "README.md");

    try {
        await fs.access(readmePath);
    } catch (error) {
        console.error("README.md not found in the current directory.");
        process.exit(1);
    }

    const content = await fs.readFile(readmePath, "utf8");
    return content;
}

function generateCode(readmeContent) {
    // Simple code generation based on README content
    const projectName = readmeContent.match(/# (.+)/)?.[1] || "MyProject";

    const code = `
// ${projectName}
// Auto-generated by CodeCraftAI

console.log('Welcome to ${projectName}!');
console.log('This is a basic implementation based on your README.md');
  `.trim();

    return code;
}

async function writeGeneratedCode(code) {
    const outputPath = path.join(process.cwd(), "index.js");
    await fs.writeFile(outputPath, code);
    console.log(`Generated code has been written to ${outputPath}`);
}

async function main() {
    console.log("CodeCraftAI - Generating your project...");

    try {
        const readmeContent = await parseReadme();
        const generatedCode = generateCode(readmeContent);
        await writeGeneratedCode(generatedCode);

        console.log("Code generation complete!");
    } catch (error) {
        console.error("An error occurred:", error.message);
        process.exit(1);
    }
}

main();
